### ISSUE TITLE
Add remove and/or removeType

### ISSUE THREAD

**Issue by jmverges** [spoonerWeb/tcabuilder#1]
Hey @spoonerWeb,

what about?

```
    public function remove()
    {
        unset($GLOBALS['TCA'][$this->table]['types'][$this->selectedType]);
    }
```
or
```
    public function removeType($type)
    {
        unset($GLOBALS['TCA'][$this->table]['types'][$type]);
    }
```

**Comment by spoonerWeb** [comment]
@jmverges Yes, sure. This library isn't finished yet, so every feedback or contribution is welcome. This repository is only a mirror, please create an issue at https://git.spooner.io/spooner-web/tcabuilder/issues/new.

I'll close the issue management here tomorrow.
